In [1]:
import numpy as np
import pandas as pd

## 1st exercise

In [18]:
depth = pd.read_csv("input1.dat", header=None)
print(depth)
d = depth.to_numpy(copy=True)

         0
0      187
1      195
2      199
3      218
4      221
...    ...
1995  9726
1996  9735
1997  9737
1998  9752
1999  9745

[2000 rows x 1 columns]


In [16]:
d[0:-1]

array([[ 187],
       [ 195],
       [ 199],
       ...,
       [9735],
       [9737],
       [9752]])

In [17]:
d[1:]

array([[ 195],
       [ 199],
       [ 218],
       ...,
       [9737],
       [9752],
       [9745]])

In [26]:
dd = d[1:]-d[0:-1]

In [33]:
len([1 for x in dd if x > 0])

1665

## 2nd exercise, rolling average

In [45]:
depth

0
0      187
1      195
2      199
3      218
4      221
...    ...
1995  9726
1996  9735
1997  9737
1998  9752
1999  9745

[2000 rows x 1 columns]

In [53]:
agg_depth = depth.rolling(3, win_type=None).sum()
agg_depth

0
0         NaN
1         NaN
2       581.0
3       612.0
4       638.0
...       ...
1995  29123.0
1996  29174.0
1997  29198.0
1998  29224.0
1999  29234.0

[2000 rows x 1 columns]

In [56]:
d = agg_depth.to_numpy(copy=True)[2:] # The 2 eliminate nans
d

array([[  581.],
       [  612.],
       [  638.],
       ...,
       [29198.],
       [29224.],
       [29234.]])

In [58]:
dd = d[1:]-d[0:-1]
dd

array([[31.],
       [26.],
       [23.],
       ...,
       [24.],
       [26.],
       [10.]])

In [59]:
len([1 for x in dd if x > 0])

1702