In [80]:
import pandas as pd
import numpy as np

with open('input') as f:
    lines_bck = f.read().splitlines()

def split(word):
    return [char for char in word]    

lines = [char for char in [x for x in lines_bck]]
lines = [split(x) for x in lines_bck]
a = np.asarray(lines)

In [81]:
octo = a.astype(int)
octo

shape = octo.shape
shape = (octo.shape[0]+2, octo.shape[1]+2)
b = np.zeros(shape, dtype=int)
b = b-10
b[1:-1, 1:-1] = octo
octo = b.copy()
octo

array([[-10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,   3,   1,   7,   2,   5,   3,   7,   6,   8,   8, -10],
       [-10,   4,   5,   6,   6,   4,   8,   3,   1,   2,   5, -10],
       [-10,   6,   3,   7,   4,   5,   1,   2,   6,   5,   3, -10],
       [-10,   8,   3,   2,   1,   1,   4,   8,   8,   8,   5, -10],
       [-10,   4,   3,   4,   2,   7,   4,   7,   7,   5,   8, -10],
       [-10,   1,   3,   6,   2,   1,   8,   8,   5,   8,   2, -10],
       [-10,   7,   5,   8,   2,   2,   1,   3,   1,   3,   2, -10],
       [-10,   6,   8,   8,   7,   8,   7,   5,   2,   6,   8, -10],
       [-10,   7,   6,   3,   5,   1,   1,   2,   7,   8,   7, -10],
       [-10,   7,   2,   4,   2,   7,   8,   7,   2,   7,   3, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10]])

In [82]:
def plus1(x):
    y = x+1
    if y < 10:
        return y
    else:
        return 0
    
def plus10(x):
    y = x+1
    if y < 10:
        return y
    else:
        return 0
    

In [83]:
octo = b.copy()
# octo[10,10] = 9
print(octo)



count = 0
flash = 0
while count < 100:
#     print(count)
    count += 1

    for i in range(1,11):
        for j in range(1,11):
            octo[i,j] = octo[i,j]+1
    #         print(i, j, octo[i,j])
    #         print
#     print(octo)

    stop = False
    while stop == False:
#         print('*')
        stop = True
        for i in range(1,11):
            for j in range(1,11):
                if octo[i,j] >= 10:
    #                 print(i,j, end=' ')
                    stop = False
                    octo[i,j]   = -10000
                    octo[i+1,j] += 1
                    octo[i,j+1] += 1
                    octo[i-1,j] += 1
                    octo[i,j-1] += 1

                    octo[i+1,j+1] += 1
                    octo[i-1,j-1] += 1
                    octo[i+1,j-1] += 1
                    octo[i-1,j+1] += 1

    for i in range(1,11):
        for j in range(1,11):
                if octo[i,j] < 0:
                    octo[i,j] = 0
                    flash += 1
                

        
        
#         print(octo[i,j], plus1()
#         octo

[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
 [-10   3   1   7   2   5   3   7   6   8   8 -10]
 [-10   4   5   6   6   4   8   3   1   2   5 -10]
 [-10   6   3   7   4   5   1   2   6   5   3 -10]
 [-10   8   3   2   1   1   4   8   8   8   5 -10]
 [-10   4   3   4   2   7   4   7   7   5   8 -10]
 [-10   1   3   6   2   1   8   8   5   8   2 -10]
 [-10   7   5   8   2   2   1   3   1   3   2 -10]
 [-10   6   8   8   7   8   7   5   2   6   8 -10]
 [-10   7   6   3   5   1   1   2   7   8   7 -10]
 [-10   7   2   4   2   7   8   7   2   7   3 -10]
 [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]]


In [84]:
octo

array([[ 4, 19, 34, 35, 37, 39, 42, 41, 40, 37, 21,  5],
       [19,  4,  4,  5,  7,  5,  0,  0,  0,  0,  0, 21],
       [34,  4,  5,  7,  0,  0,  0,  0,  0,  0,  0, 37],
       [36,  4,  6,  0,  0,  0,  6,  6,  0,  0,  0, 39],
       [38,  4,  6,  0,  0,  5,  3,  3,  5,  0,  0, 40],
       [41,  5,  6,  6,  9,  3,  2,  2,  3,  5,  0, 39],
       [40,  2,  6,  4,  7,  2,  2,  2,  2,  3,  3, 37],
       [38,  2,  9,  7,  9,  2,  2,  2,  2,  2,  2, 35],
       [35,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 35],
       [35,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2, 34],
       [20,  0,  3,  2,  2,  2,  2,  2,  2,  2,  8, 19],
       [ 5, 20, 35, 35, 35, 35, 35, 35, 35, 34, 19,  4]])

In [85]:
35

35

In [86]:
flash

1688

In [87]:
octo = b.copy()
# octo[10,10] = 9
print(octo)



count = 0
flash = 0
STOP = False
while STOP == False:
#     print(count)
    count += 1

    for i in range(1,11):
        for j in range(1,11):
            octo[i,j] = octo[i,j]+1
    #         print(i, j, octo[i,j])
    #         print
#     print(octo)

    stop = False
    while stop == False:
#         print('*')
        stop = True
        for i in range(1,11):
            for j in range(1,11):
                if octo[i,j] >= 10:
    #                 print(i,j, end=' ')
                    stop = False
                    octo[i,j]   = -10000
                    octo[i+1,j] += 1
                    octo[i,j+1] += 1
                    octo[i-1,j] += 1
                    octo[i,j-1] += 1

                    octo[i+1,j+1] += 1
                    octo[i-1,j-1] += 1
                    octo[i+1,j-1] += 1
                    octo[i-1,j+1] += 1

    flash = 0
    for i in range(1,11):
        for j in range(1,11):
                if octo[i,j] < 0:
                    octo[i,j] = 0
                    flash += 1
    if flash == 100:
        STOP = True
        print(count)

        
        
#         print(octo[i,j], plus1()
#         octo

[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
 [-10   3   1   7   2   5   3   7   6   8   8 -10]
 [-10   4   5   6   6   4   8   3   1   2   5 -10]
 [-10   6   3   7   4   5   1   2   6   5   3 -10]
 [-10   8   3   2   1   1   4   8   8   8   5 -10]
 [-10   4   3   4   2   7   4   7   7   5   8 -10]
 [-10   1   3   6   2   1   8   8   5   8   2 -10]
 [-10   7   5   8   2   2   1   3   1   3   2 -10]
 [-10   6   8   8   7   8   7   5   2   6   8 -10]
 [-10   7   6   3   5   1   1   2   7   8   7 -10]
 [-10   7   2   4   2   7   8   7   2   7   3 -10]
 [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]]
403
