In [24]:
import pandas as pd
import numpy as np

with open('input') as f:
    lines_bck = f.read().splitlines()

def split(word):
    return [char for char in word]    
    
lines = [char for char in [x for x in lines_bck]]
lines = [split(x) for x in lines_bck]
a = np.asarray(lines)

In [40]:
shape = a.shape
shape = (a.shape[0]+2, a.shape[1]+2)
b = np.zeros(shape, dtype=int)
b = b+99
print(b.shape)
print(b[0,0])

(102, 102)
99


In [41]:
b[1:-1, 1:-1] = a


In [43]:
b[:,0]

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [44]:
b[:,1]

array([99,  8,  6,  5,  3,  4,  3,  4,  5,  9,  8,  9,  9,  9,  8,  9,  9,
        9,  8,  7,  6,  5,  6,  7,  9,  8,  7,  8,  7,  8,  9,  5,  6,  8,
        9,  8,  9,  6,  7,  9,  9,  9,  8,  7,  6,  5,  4,  6,  7,  8,  9,
        8,  6,  7,  8,  9,  8,  7,  7,  8,  9,  2,  1,  3,  4,  9,  8,  7,
        4,  3,  2,  0,  3,  4,  7,  9,  2,  1,  9,  5,  4,  3,  2,  3,  4,
        5,  6,  7,  8,  9,  7,  5,  4,  5,  5,  7,  8,  9,  9,  9,  8, 99])

In [45]:
b[:,-2]

array([99,  9,  2,  0,  9,  7,  9,  8,  7,  6,  7,  8,  9,  2,  3,  9,  8,
        4,  3,  4,  5,  8,  9,  3,  4,  5,  9,  7,  9,  8,  7,  8,  9,  6,
        5,  4,  3,  5,  6,  9,  8,  7,  6,  5,  6,  7,  8,  9,  3,  2,  1,
        2,  9,  2,  0,  1,  9,  5,  4,  2,  1,  0,  9,  8,  6,  6,  5,  4,
        2,  1,  2,  3,  4,  5,  7,  8,  9,  8,  9,  9,  9,  8,  7,  7,  8,
        9,  7,  9,  9,  9,  8,  7,  6,  5,  7,  6,  5,  4,  9,  9,  9, 99])

In [46]:
b[:,-1]

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [53]:
suma = 0
for x in range(1,b.shape[0]-1):
    for y in range(1,b.shape[0]-1):
#         print(x,y)
        if ((b[x,y] < b[x-1,y]) and (b[x,y] < b[x+1,y]) and (b[x,y] < b[x,y-1]) and (b[x,y] < b[x,y+1])):
            suma += b[x,y] +1

suma

564

## second part

In [67]:
bassin_lens = []
for x in range(1,b.shape[0]-1):
    for y in range(1,b.shape[0]-1):
#         print(x,y)
        if ((b[x,y] < b[x-1,y]) and (b[x,y] < b[x+1,y]) and (b[x,y] < b[x,y-1]) and (b[x,y] < b[x,y+1])):
            bassin_pos = set()
            bassin_pos.add((x,y))
            prev_len = 0
            while len(bassin_pos) > prev_len: # mientras se sigan agregando puntos al bassin
                prev_len = len(bassin_pos)
                bassin_pos_tmp = bassin_pos.copy()
                for point in bassin_pos_tmp:
                    if b[point[0]+1, point[1]] < 9:
                        bassin_pos.add((point[0]+1, point[1]))
                    if b[point[0]-1, point[1]] < 9:
                        bassin_pos.add((point[0]-1, point[1]))
                    if b[point[0], point[1]+1] < 9:
                        bassin_pos.add((point[0], point[1]+1))
                    if b[point[0], point[1]-1] < 9:
                        bassin_pos.add((point[0], point[1]-1))
                
            bassin_lens.append(prev_len)
            
            


In [74]:
for i in range(3):
    max_value = max(bassin_lens)
    max_index = bassin_lens.index(max_value)
    print(max_index, max_value)
    bassin_lens.pop(max_index)
#     bassin_lens


70 105
179 103
173 96


In [75]:
105*103*96

1038240

In [64]:
for point in bassin_pos:
    print(point[0])

100
