In [163]:
import pandas as pd
import numpy as np

with open('inputtest') as f:
    lines_bck = f.read().splitlines()

def split(word):
    return [char for char in word]    

lines = [char for char in [x for x in lines_bck]]
lines = [split(x) for x in lines_bck]
a = np.asarray(lines).astype(int)

In [164]:
a

array([[1, 1, 6, 3, 7, 5, 1, 7, 4, 2],
       [1, 3, 8, 1, 3, 7, 3, 6, 7, 2],
       [2, 1, 3, 6, 5, 1, 1, 3, 2, 8],
       [3, 6, 9, 4, 9, 3, 1, 5, 6, 9],
       [7, 4, 6, 3, 4, 1, 7, 1, 1, 1],
       [1, 3, 1, 9, 1, 2, 8, 1, 3, 7],
       [1, 3, 5, 9, 9, 1, 2, 4, 2, 1],
       [3, 1, 2, 5, 4, 2, 1, 6, 3, 9],
       [1, 2, 9, 3, 1, 3, 8, 5, 2, 1],
       [2, 3, 1, 1, 9, 4, 4, 5, 8, 1]])

In [84]:
a.shape

(10, 10)

In [97]:
path = []
# old = a[0,0]
i = j = 0
while i < a.shape[0]-2 and j < a.shape[1]-2:
    print(i,j)

    right       = a[i,j+1] + a[i,j+2]
    diag_right  = a[i,j+1] + a[i+1,j+1]
    diag_down   = a[i+1,j] + a[i+1,j+1]
    down        = a[i+1,j] + a[i+2,j]
    
    direction  = [right, diag_right, diag_down, down]
    print(direction)
    min_val = min(direction)
    min_ind = direction.index(min_val)
    
    if min_ind == 0 or min_ind == 1:
        j += 1
        print('right')
    else:
        i += 1    
        print('down')
    path.append(a[i,j])
    print(path)
    print('***************')

0 0
[7, 4, 4, 3]
down
[1]
***************
1 0
[11, 4, 3, 5]
down
[1, 2]
***************
2 0
[4, 7, 9, 10]
right
[1, 2, 1]
***************
2 1
[9, 12, 15, 10]
right
[1, 2, 1, 3]
***************
2 2
[11, 10, 13, 15]
right
[1, 2, 1, 3, 6]
***************
2 3
[6, 14, 13, 7]
right
[1, 2, 1, 3, 6, 5]
***************
2 4
[2, 4, 12, 13]
right
[1, 2, 1, 3, 6, 5, 1]
***************
2 5
[4, 2, 4, 4]
right
[1, 2, 1, 3, 6, 5, 1, 1]
***************
2 6
[5, 8, 6, 8]
right
[1, 2, 1, 3, 6, 5, 1, 1, 3]
***************
2 7
[10, 8, 11, 6]
down
[1, 2, 1, 3, 6, 5, 1, 1, 3, 5]
***************
3 7
[15, 7, 2, 2]
down
[1, 2, 1, 3, 6, 5, 1, 1, 3, 5, 1]
***************
4 7
[2, 4, 4, 5]
right
[1, 2, 1, 3, 6, 5, 1, 1, 3, 5, 1, 1]
***************


In [88]:
np.asarray(path).sum()

30

In [95]:
path

[1, 2, 1, 3, 6, 5, 1, 1, 3, 5, 1, 1]

In [78]:
import itertools

counter = 0
all_paths = []


window_size = 5
# window_size = a.shape[0]
stuff = range((window_size-1)*2)

    

for subset in itertools.combinations(stuff, a.shape[0]-1):
#     counter += 1
#     if counter%10_000 == 0:
#         print(counter, end=' ')
    i = j = 0
    path = [a[0,0]]
    for direc in range((a.shape[0]-1)*2):
#         print(direc)
        if direc in subset:
            i += 1
        else:
            j += 1
#         print(i,j)
        path.append(a[i,j])
    all_paths.append(np.asarray(path).sum())

minim_path = np.asarray(all_paths).min()-a[0,0]

In [79]:
minim_path

40

## Dijks

In [18]:
import numpy as np

with open('input') as f:
    lines_bck = f.read().splitlines()

def split(word):
    return [char for char in word]    

lines = [char for char in [x for x in lines_bck]]
lines = [split(x) for x in lines_bck]
a = np.asarray(lines).astype(int)
a

array([[7, 1, 3, ..., 1, 1, 9],
       [8, 8, 1, ..., 8, 4, 1],
       [1, 5, 1, ..., 9, 3, 1],
       ...,
       [5, 1, 6, ..., 3, 5, 6],
       [2, 1, 9, ..., 7, 3, 7],
       [2, 1, 2, ..., 1, 2, 3]])

In [19]:
from queue import PriorityQueue

In [20]:
class Graph:
    def __init__(self, num_of_vertices):
        self.v = num_of_vertices
        self.edges = [[-1 for i in range(num_of_vertices)] for j in range(num_of_vertices)]
        self.visited = []
        
    def add_edge(self, u, v, weight1, weight2):
        self.edges[u][v] = weight1
        self.edges[v][u] = weight2

In [21]:
def dijkstra(graph, start_vertex):
    D = {v:float('inf') for v in range(graph.v)}
    D[start_vertex] = 0

    pq = PriorityQueue()
    pq.put((0, start_vertex))

    while not pq.empty():
        (dist, current_vertex) = pq.get()
        graph.visited.append(current_vertex)

        for neighbor in range(graph.v):
            if graph.edges[current_vertex][neighbor] != -1:
                distance = graph.edges[current_vertex][neighbor]
                if neighbor not in graph.visited:
                    old_cost = D[neighbor]
                    new_cost = D[current_vertex] + distance
                    if new_cost < old_cost:
                        pq.put((new_cost, neighbor))
                        D[neighbor] = new_cost
    return D

In [5]:
dimX = dimY = a.shape[0] # include extra column to avoid complex border conditions

matrix = np.ones(shape=(dimX+1, dimY+1)).astype(int)*10000
matrix[0:-1, 0:-1] = a
print(matrix)


def node_num(i,j):
    return j+(dimX+1)*i



g = Graph((dimX+1)*(dimY+1))  # I take out the element 100,100 because it isn't needed

for i in range(dimX):
    for j in range(dimY):        
        g.add_edge(node_num(i, j), node_num(i+1, j), matrix[i+1, j], matrix[i, j])
        g.add_edge(node_num(i, j), node_num(i, j+1), matrix[i, j+1], matrix[i, j])
#         print(i,j, node_num(i, j))
#         print(node_num(i, j), node_num(i+1, j))
#         print(node_num(i, j), node_num(i, j+1))


[[    7     1     3 ...     1     9 10000]
 [    8     8     1 ...     4     1 10000]
 [    1     5     1 ...     3     1 10000]
 ...
 [    2     1     9 ...     3     7 10000]
 [    2     1     2 ...     2     3 10000]
 [10000 10000 10000 ... 10000 10000 10000]]


In [6]:
D = dijkstra(g, 0)

print(D)
path_lengh = D[node_num(dimX-1, dimY-1)] 
path_lengh

441

In [193]:
(dimX+1)*(dimY+1)-dimX-2

10099

## Second part

In [1]:
from queue import PriorityQueue

class Graph:
    def __init__(self, num_of_vertices):
        self.v = num_of_vertices
        self.edges = [[-1 for i in range(num_of_vertices)] for j in range(num_of_vertices)]
        self.visited = []
        
    def add_edge(self, u, v, weight1, weight2):
        self.edges[u][v] = weight1
        self.edges[v][u] = weight2
        
def dijkstra(graph, start_vertex):
    D = {v:float('inf') for v in range(graph.v)}
    D[start_vertex] = 0

    pq = PriorityQueue()
    pq.put((0, start_vertex))

    while not pq.empty():
        (dist, current_vertex) = pq.get()
        graph.visited.append(current_vertex)

        for neighbor in range(graph.v):
            if graph.edges[current_vertex][neighbor] != -1:
                distance = graph.edges[current_vertex][neighbor]
                if neighbor not in graph.visited:
                    old_cost = D[neighbor]
                    new_cost = D[current_vertex] + distance
                    if new_cost < old_cost:
                        pq.put((new_cost, neighbor))
                        D[neighbor] = new_cost
    return D      


In [8]:
import numpy as np
from copy import deepcopy

with open('inputtest') as f:
    lines_bck = f.read().splitlines()

def split(word):
    return [char for char in word]    

lines = [char for char in [x for x in lines_bck]]
lines = [split(x) for x in lines_bck]
a = np.asarray(lines).astype(np.short)
a

array([[1, 1, 6, 3, 7, 5, 1, 7, 4, 2],
       [1, 3, 8, 1, 3, 7, 3, 6, 7, 2],
       [2, 1, 3, 6, 5, 1, 1, 3, 2, 8],
       [3, 6, 9, 4, 9, 3, 1, 5, 6, 9],
       [7, 4, 6, 3, 4, 1, 7, 1, 1, 1],
       [1, 3, 1, 9, 1, 2, 8, 1, 3, 7],
       [1, 3, 5, 9, 9, 1, 2, 4, 2, 1],
       [3, 1, 2, 5, 4, 2, 1, 6, 3, 9],
       [1, 2, 9, 3, 1, 3, 8, 5, 2, 1],
       [2, 3, 1, 1, 9, 4, 4, 5, 8, 1]], dtype=int16)

In [9]:
dimX = dimY = a.shape[0] # include extra column to avoid complex border conditions

matrix = np.ones(shape=(dimX+2, dimY+2)).astype(np.short)*10000
matrix[1:-1, 1:-1] = a
print(matrix)
print(matrix.shape)
# type(matrix)

[[10000 10000 10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000     1     1     6     3     7     5     1     7     4     2 10000]
 [10000     1     3     8     1     3     7     3     6     7     2 10000]
 [10000     2     1     3     6     5     1     1     3     2     8 10000]
 [10000     3     6     9     4     9     3     1     5     6     9 10000]
 [10000     7     4     6     3     4     1     7     1     1     1 10000]
 [10000     1     3     1     9     1     2     8     1     3     7 10000]
 [10000     1     3     5     9     9     1     2     4     2     1 10000]
 [10000     3     1     2     5     4     2     1     6     3     9 10000]
 [10000     1     2     9     3     1     3     8     5     2     1 10000]
 [10000     2     3     1     1     9     4     4     5     8     1 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]]
(12, 12)


In [10]:


def node_num(i,j):
    return j+(dimX+2)*i

def cycle(x, n):
    if x == 10000:
        return x
    x = x+n
    if x >= 10:
        return 1
    else: 
        return x 


In [11]:
# for i in range(1,dimX+1):
#     j = dimY+1
#     print(D[node_num(i,j)])
    
# print()
# for j in range(1,dimY+1):
#     i = dimX+1
#     print(D[node_num(i,j)])



In [12]:
node_link = {}
for i in range(1,dimX+1):
#     print(node_num(i,0), node_num(i,dimY+1))
    node_link[node_num(i,dimY+1)] = node_num(i,0)
    
print()
for j in range(1,dimY+1):
    node_link[node_num(dimX+1,j)] = node_num(0,j)
#     print(D[node_num(i,j)])


In [13]:
node_link

{23: 12,
 35: 24,
 47: 36,
 59: 48,
 71: 60,
 83: 72,
 95: 84,
 107: 96,
 119: 108,
 131: 120,
 133: 1,
 134: 2,
 135: 3,
 136: 4,
 137: 5,
 138: 6,
 139: 7,
 140: 8,
 141: 9,
 142: 10}

In [14]:
min_val_all = []
min_node = dimY+2+1
print(min_node)

num_tiles = 5+5-1

for I in range(num_tiles): #number of tiles that mast cross the elve
    print(I)
    g = Graph((dimX+2)*(dimY+2)) 

    for i in range(dimX+1):
        for j in range(dimY+1):        
            g.add_edge(node_num(i, j), node_num(i+1, j), cycle(matrix[i+1, j], I), cycle(matrix[i, j], I))
            g.add_edge(node_num(i, j), node_num(i, j+1), cycle(matrix[i, j+1], I), cycle(matrix[i, j], I))

    D  = dijkstra(g, min_node)
#     print(D)

    min_val  = 1000000
#     min_node = 0

    for i in range(1,dimX+1):
        j = dimY+1
        if D[node_num(i,j)] < min_val:
            min_val = D[node_num(i,j)]
            min_node = node_num(i,j)

    for j in range(1,dimY+1):
        i = dimX+1
        if D[node_num(i,j)] < min_val:
            min_val = D[node_num(i,j)]
            min_node = node_num(i,j)
    
    print('min_val: ', min_val, 'output_node: ', min_node, 'input_node: ', node_link[min_node])
    min_node = node_link[min_node]
    
    min_val_all.append(min_val-10000)
    



13
0
min_val:  10021 output_node:  133 input_node:  1
1
min_val:  10032 output_node:  133 input_node:  1
2
min_val:  10042 output_node:  133 input_node:  1
3
min_val:  10043 output_node:  133 input_node:  1
4
min_val:  10040 output_node:  35 input_node:  24
5
min_val:  10041 output_node:  59 input_node:  48
6
min_val:  10031 output_node:  137 input_node:  5
7
min_val:  10009 output_node:  59 input_node:  48
8
min_val:  10010 output_node:  134 input_node:  2


In [10]:
min_val_all

[289, 310, 230, 278, 243, 209, 167, 119, 124]

In [17]:
np.asarray(min_val_all).sum()-min_val_all[-1] +210 #D[node_num(dimX-1, dimY-1)]

2055

In [16]:
len(D)
D[10402]

10210

In [54]:
for i in range(1,dimX+1):
    print()
    for j in range(1,dimY+1):
        print(matrix[i,j], end='')




1163751742
1381373672
2136511328
3694931569
7463417111
1319128137
1359912421
3125421639
1293138521
2311944581

In [55]:
for i in range(1,dimX+1):
    print()
    for j in range(1,dimY+1):
        print(cycle(matrix[i,j], 1), end='')



2274862853
2492484783
3247622439
4715142671
8574528222
2421239248
2461123532
4236532741
2314249632
3422155692