In [1]:
# import pandas as pd
import numpy as np

with open('inputtest') as f:
    lines_bck = f.read().splitlines()

# def split(word):
#     return [char for char in word]    

# lines = [char for char in [x for x in lines_bck]]
lines = [x.split(',') for x in lines_bck] #[:-13]]
# lines = np.asarray(lines)
# n = 
lines = [[int(row[0]), int(row[1])] for row in lines]
# [row for row in lines]
lines = np.asarray(lines)
lines

array([[ 6, 10],
       [ 0, 14],
       [ 9, 10],
       [ 0,  3],
       [10,  4],
       [ 4, 11],
       [ 6,  0],
       [ 6, 12],
       [ 4,  1],
       [ 0, 13],
       [10, 12],
       [ 3,  4],
       [ 3,  0],
       [ 8,  4],
       [ 1, 10],
       [ 2, 14],
       [ 8, 10],
       [ 9,  0]])

In [2]:
m = np.max(lines[:,0]+1)
n = np.max(lines[:,1]+1)
print(n,m)

15 11


In [3]:
sheet = np.zeros((n,m))
for line in lines:
    sheet[line[1], line[0]] = 1
    
print(sheet.shape)
sheet

(15, 11)


array([[0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
n_Ty = (n-1)//2
m_Ty = n

identity = np.identity(n_Ty)
rotation = np.rot90(identity, k=1, axes=(0¶, 1))

fold_Ty = np.concatenate((identity, np.zeros((n_Ty,1)), rotation), axis=1)
fold_Ty
# fold_y7[:, n_y7] = 0
# fold_y7

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [5]:
sheet = fold_Ty @ sheet
print(sheet.shape)
sheet

(7, 11)


array([[1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 2., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
sheet = np.heaviside(sheet,0)
sheet

array([[1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
print(sheet.sum())


17.0


In [8]:
n = sheet.shape[0]
m = sheet.shape[1]
print(n,m)

n_Tx = m
m_Tx = (n-1)//2

identity = np.identity((n_Tx-1)//2)
rotation = np.rot90(identity, k=1, axes=(0, 1))


fold_Tx = np.concatenate((identity, np.zeros((1,(n_Tx-1)//2)), rotation), axis=0)
print(fold_Tx.shape)
fold_Tx

7 11
(11, 5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [10]:
sheet = np.heaviside(sheet @ fold_Tx, 0)
sheet
# identity

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# sheet = sheet_Tx
sheet.sum()

16.0

## FIRST FOLD
fold along x=655
fold along y=447
fold along x=327
fold along y=223
fold along x=163
fold along y=111
fold along x=81
fold along y=55
fold along x=40
fold along y=27
¶
fold along y=13
fold along y=6


In [13]:
import numpy as np

with open('input') as f:
    lines_bck = f.read().splitlines()

# def split(word):
#     return [char for char in word]    

# lines = [char for char in [x for x in lines_bck]]
lines = [x.split(',') for x in lines_bck[:-13]]
# lines = np.asarray(lines)
# n = 
lines = [[int(row[0]), int(row[1])] for row in lines]
# [row for row in lines]
lines = np.asarray(lines)
lines

array([[647, 840],
       [ 99, 833],
       [318,  50],
       ...,
       [348, 421],
       [764, 392],
       [403, 352]])

In [16]:
np.max(lines, axis=0)

array([1309,  892])

In [23]:
# Create sheet
m = np.max(lines[:,0]+2)
n = np.max(lines[:,1]+3)
print(n,m)

sheet = np.zeros((n,m))
for line in lines:
    sheet[line[1], line[0]] = 1

895 1311


In [24]:
# Create rotator matrix in x axis

n = sheet.shape[0]
m = sheet.shape[1]
print(n,m)

n_Tx = m
m_Tx = (n-1)//2

identity = np.identity((n_Tx)//2)
rotation = np.rot90(identity, k=1, axes=(0, 1))


fold_Tx = np.concatenate((identity, np.zeros((1,(n_Tx-1)//2)), rotation), axis=0)
print(fold_Tx.shape)


895 1311
(1311, 655)


In [25]:
sheet = np.heaviside(sheet @ fold_Tx, 0)
sheet

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
sheet.sum()

687.0

In [27]:
sheet.shape

(895, 655)

### answer 1 687

# Second part

In [42]:

with open('input') as f:
    lines_bck = f.read().splitlines()

# def split(word):
#     return [char for char in word]    

# lines = [char for char in [x for x in lines_bck]]
lines = [x.split(',') for x in lines_bck[:-13]]
# lines = np.asarray(lines)
# n = 
lines = [[int(row[0]), int(row[1])] for row in lines]
# [row for row in lines]
lines = np.asarray(lines)

# Create sheet
m = np.max(lines[:,0]+2) # to match the position of folding
n = np.max(lines[:,1]+3)
print(n,m)

    


895 1311


In [43]:
sheet = np.zeros((n,m))
for line in lines:
    sheet[line[1], line[0]] = 1



# Create rotator matrix in x axis


for i in range(5):

    n = sheet.shape[0]
    m = sheet.shape[1]
    print(n,m)

    n_Tx = m
    m_Tx = (n-1)//2

    identity = np.identity((n_Tx)//2)
    rotation = np.rot90(identity, k=1, axes=(0, 1))


    fold_Tx = np.concatenate((identity, np.zeros((1,(n_Tx-1)//2)), rotation), axis=0)

    sheet = np.heaviside(sheet @ fold_Tx, 0)
    print(sheet.shape)


    # Create rotator matrix in y axis


    n = sheet.shape[0]
    m = sheet.shape[1]

    n_Ty = (n-1)//2
    m_Ty = n

    identity = np.identity(n_Ty)
    rotation = np.rot90(identity, k=1, axes=(0, 1))

    fold_Ty = np.concatenate((identity, np.zeros((n_Ty,1)), rotation), axis=1)
    # fold_Ty
    sheet = np.heaviside(fold_Ty @ sheet, 0)
    print(sheet.shape)
    # sheet = np.heaviside(sheet,0)

    
    
for i in range(2):
    n = sheet.shape[0]
    m = sheet.shape[1]

    n_Ty = (n-1)//2
    m_Ty = n

    identity = np.identity(n_Ty)
    rotation = np.rot90(identity, k=1, axes=(0, 1))

    fold_Ty = np.concatenate((identity, np.zeros((n_Ty,1)), rotation), axis=1)
    # fold_Ty
    sheet = np.heaviside(fold_Ty @ sheet, 0)
    print(sheet.shape)
    

895 1311
(895, 655)
(447, 655)
447 655
(447, 327)
(223, 327)
223 327
(223, 163)
(111, 163)
111 163
(111, 81)
(55, 81)
55 81
(55, 40)
(27, 40)
(13, 40)
(6, 40)


In [44]:
sheet.sum()

98.0

In [47]:
sheet.astype(int)

array([[1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0]])

In [ ]:
import pandas as pd

pd.wr