In [1]:
import pandas as pd
import numpy as np

with open('input') as f:
    lines_bck = f.read().splitlines()

# df = pd.read_csv('input', header=None, dtype=str)
# df

In [2]:
lines = [x.replace(' -> ',',') for x in lines_bck]
lenlines = len(lines)
print(lenlines)
lines[:3]

500


['580,438,580,817', '220,987,199,966', '300,674,300,523']

In [3]:
# linsplit = [x.split(',') for x in lines]
linsplit = [list(map(int, x.split(','))) for x in lines]
linsplit[:3]

[[580, 438, 580, 817], [220, 987, 199, 966], [300, 674, 300, 523]]

In [4]:
arr = np.array(linsplit)
arr

array([[580, 438, 580, 817],
       [220, 987, 199, 966],
       [300, 674, 300, 523],
       ...,
       [ 20,  29, 980, 989],
       [ 37,  41, 255,  41],
       [368, 823, 302, 823]])

11 11 10 11
989 989 990 989
10 990 11 989



......
......
......
......
......
......

In [114]:
stack = []
stack_set = []


for r in arr:
#     print(r)
    
    x0 = r[0]
    x1 = r[2]
    y0 = r[1]
    y1 = r[3]
    
    if x0 == x1:
        y_min = min(y0, y1)
        y_max = max(y0, y1)
        for y in range(y_min, y_max+1):
#             stack.append([x0,y])
            stack.append((x0,y))
            
            
    if y0 == y1:
        x_min = min(x0, x1)
        x_max = max(x0, x1)
        for x in range(x_min, x_max+1):
#             stack.append([x,y0])
            stack.append((x,y0))

#     break
np_stack = np.array(stack)

In [70]:
np_stack

array([[580, 438],
       [580, 439],
       [580, 440],
       ...,
       [366, 823],
       [367, 823],
       [368, 823]])

In [48]:
arr

array([[580, 438, 580, 817],
       [220, 987, 199, 966],
       [300, 674, 300, 523],
       ...,
       [ 20,  29, 980, 989],
       [ 37,  41, 255,  41],
       [368, 823, 302, 823]])

In [86]:
min0 = arr[:,0].min()
min2 = arr[:,2].min()
min1 = arr[:,1].min()
min3 = arr[:,3].min()

max0 = arr[:,0].max()
max2 = arr[:,2].max()
max1 = arr[:,1].max()
max3 = arr[:,3].max()

print(min0, min1, min2, min3)
print(max0, max1, max2, max3)

minX = min(min0, min2)
maxX = max(max0, max2)
minY = min(min1, min3)
maxY = max(max1, max3)
print(minX, maxX, minY, maxY)
 

# minX = 0
# maxX = 5
# minY = 0
# maxY = 5
final_ans = 0

len_np_stack = np_stack.shape[0]

for y in range(minY, maxY+1):
    print('y', y)
#     id_y = y-minY
#     print('')
    for x in range(minX, maxX+1):
        print(x, end=' ')
        ans = 0
#         id_x = x-minX
#         print('.', end='')
        
        for r in np_stack:
            if r[0] == x and r[1] == y:
                ans += 1
                
        if ans > 1:
            final_ans += 1


11 11 10 11
989 989 990 989
10 990 11 989
y 11
10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270

KeyboardInterrupt: 

In [ ]:
final_ans

In [78]:
arr    

array([[580, 438, 580, 817],
       [220, 987, 199, 966],
       [300, 674, 300, 523],
       ...,
       [ 20,  29, 980, 989],
       [ 37,  41, 255,  41],
       [368, 823, 302, 823]])

In [96]:
resto = arr.shape[0]


for ind, r in enumerate(arr):
#     print(ind, r)
    x0 = r[0]
    x1 = r[2]
    y0 = r[1]
    y1 = r[3]
    vx = x1-x0
    vy = y1-y0
    
    for i in range(ind+1, resto):
#         print(i)
        rp = arr[i,:]
        xp0 = rp[0]
        xp1 = rp[2]
        yp0 = rp[1]
        yp1 = rp[3]
        vpx = xp1-xp0
        vpy = yp1-yp0
#         print(rp)
        int_prod = vx*vpx + vy*vpy
    
        if int_prod == 0:
            if 
            print(r, rp)
            
        
    break
    

[580 438 580 817] [890 430 854 430]
[580 438 580 817] [700 139 531 139]
[580 438 580 817] [779 635 420 635]
[580 438 580 817] [601  11 893  11]
[580 438 580 817] [471 490 900 490]
[580 438 580 817] [314 475 698 475]
[580 438 580 817] [ 15 101 335 101]
[580 438 580 817] [142 321 781 321]
[580 438 580 817] [248 586 130 586]
[580 438 580 817] [640 798 153 798]
[580 438 580 817] [ 24 711 147 711]
[580 438 580 817] [334 309  43 309]
[580 438 580 817] [765 630 892 630]
[580 438 580 817] [ 41 300 606 300]
[580 438 580 817] [229 348 379 348]
[580 438 580 817] [196 489 842 489]
[580 438 580 817] [941 238 206 238]
[580 438 580 817] [742  28 402  28]
[580 438 580 817] [513 630 823 630]
[580 438 580 817] [204 663 179 663]
[580 438 580 817] [716 192 916 192]
[580 438 580 817] [529 971 752 971]
[580 438 580 817] [250 228 348 228]
[580 438 580 817] [245 760 631 760]
[580 438 580 817] [328 767 558 767]
[580 438 580 817] [103 626 937 626]
[580 438 580 817] [285 533 690 533]
[580 438 580 817] [205  47 8

In [95]:
arr

array([[580, 438, 580, 817],
       [220, 987, 199, 966],
       [300, 674, 300, 523],
       ...,
       [ 20,  29, 980, 989],
       [ 37,  41, 255,  41],
       [368, 823, 302, 823]])

In [98]:
len(stack)



98816

In [99]:
set(stack)

TypeError: unhashable type: 'list'

In [100]:
stack_set = set(tuple(x) for x in stack)

In [102]:
len(stack_set)

93138

In [103]:
98816-931385678

5678

In [105]:
len(stack_set)

98816

In [106]:
len(set(stack_set))

93138

In [133]:
stack_unique = list(set(stack))
len(stack_unique)
# for x in stack_set2:
#     print(stack_set.count(x))

93138

In [138]:
adentro = 0
for a in stack_unique:
    print('.', end=' ')
# a = (580,439)
# print(a)
    count = stack.count(a) 
    if count > 1:
        adentro += 1

print('ADENTRO:', adentro)

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 

In [117]:
len(stack)

98816

## Second

In [17]:
stack = []
# stack_set = []


for r in arr:
#     print(r)
    
    x0 = r[0]
    x1 = r[2]
    y0 = r[1]
    y1 = r[3]
    vx = (x1-x0)
    vy = (y1-y0)

    if vx != 0:
        vx = vx//abs(vx)

    if vy != 0:
        vy = vy//abs(vy)

    i = 0
    j = 0 
    x = x0
    y = y0
#     print(x, y, vx, vy)
    print('.', end='')
    while ((x != x1) or (y != y1)):
#         print('.', end='')
        x = i*vx+x0
        y = j*vy+y0
#         print(x,y)
        stack.append((x,y))
        i += 1
        j += 1

    

#     break

....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

In [19]:
len(stack)

189708

In [20]:
stack_unique = list(set(stack))
len(stack_unique)

165996

In [21]:
adentro2 = 0

for a in stack_unique:
    print('.', end=' ')
# a = (580,439)
# print(a)
    count = stack.count(a) 
    if count > 1:
        adentro2 += 1

print('ADENTRO:', adentro2)

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 

In [5]:
arr[:2,:]

array([[580, 438, 580, 817],
       [220, 987, 199, 966]])